services:
  # --- база данных ---
  db:
    image: postgres:15-alpine
    restart: always
    secrets:
      - db_user
      - db_password
      - db_name
    environment:
      - POSTGRES_DB_FILE=/run/secrets/db_name
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5

  # --- миграции ---
  migrate:
    image: migrate/migrate
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:password@db:5432/postgres?sslmode=disable",
      "up"
    ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    networks:
      - backend
  
  # --- кеш ---
  cache:
    image: redis:7-alpine
    command: ["/bin/sh", "-c", "redis-server --requirepass $$(cat /run/secrets/redis_password)"]
    secrets:
      - redis_password
    environment:
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
    restart: always
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  # --- синхронизатор ---
  syncer:
    build: 
      context: .
      dockerfile: ./cmd/syncer/Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file: .env
    secrets:
      - db_user
      - db_password
      - db_name
      - redis_password
    networks:
      - backend

  # --- основное приложение ---
  app:
    build: 
      context: .
      dockerfile: ./cmd/app/Dockerfile
    restart: unless-stopped
    env_file: .env
    secrets:
      - db_user
      - db_password
      - db_name
      - redis_password
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "8080:8080"
  
  # --------- прометеус ---------
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - backend
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  
  # -------- grafana --------
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - backend
    ports:
      - "3000:3000"
    secrets:
      - grafana_admin_user
      - grafana_admin_password
    environment:
      - GF_SECURITY_ADMIN_USER__FILE=/run/secrets/grafana_admin_user
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  pgdata:
  grafana-storage:
  
secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  db_name:
    file: ./secrets/db_name.txt
  redis_password:
    file: ./secrets/redis_password.txt
  grafana_admin_user:
    file: ./secrets/grafana_admin_user.txt
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.txt

networks:
  backend:
    driver: bridge
